name: Generate Translations
on:
  push:
    branches:
      - develop

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress POT/PO/MO Generator
      uses: NikosBikas/wp-pot-po-mo-generator@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
