name: Generate Translations
on: workflow_dispatch
jobs:
  generate-translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress POT/PO/MO Generator
      uses: NikosBikas/wp-pot-po-mo-generator@master
      with:
        destination_path: './languages'
        slug: 'axtra'
        text_domain: 'axtra'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
